name: counter
description: This is a simple counter app meant to demo Hive's persistence and speed.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  hive:
  hive_flutter:


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
