name: contacts
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

# sdk: ">=2.7.0 <3.0.0"
environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  hive:
  hive_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  hive_generator:


flutter:
  uses-material-design: true
